### ISSUE TITLE
Changes not apply

### ISSUE THREAD

**Issue by Fanalys** [digitalcraftsman/hugo-agency-theme#11]
Hi, 

I'm using your theme and I follow the steps of the Readme but when I launch my website, the text fields are empty : 

![capture du 2015-11-26 21-29-17](https://cloud.githubusercontent.com/assets/15721041/11430309/cf64e4be-9484-11e5-8967-0c720d2557d2.png)

Did I do something wrong ?
Thanks for the help!

**Comment by digitalcraftsman** [comment]
Hi @Fanalys,

while testing the latest verions of this theme myself I don't had the issues you mentioned. In order to locate the error, could you anwser a few questions:
- does Hugo output some error messages in the terminal? If yes, please put them into your response.
- do you have modified any templates of the theme?
- which version of Hugo are you using?

**Comment by Fanalys** [comment]
Well, I've reboot the hugo server and the text fields appeared.. Problem solved ! 

My apologies!

Thanks for ur work !

**Comment by digitalcraftsman** [comment]
No problem.
