### ISSUE TITLE
description can only write in one line? and how to insert image?

### ISSUE THREAD

**Issue by blackmatch** [digitalcraftsman/hugo-agency-theme#12]
hello, can you tell me how to edit my article in multi-line ? and how to insert a image in my article since including description of *.yaml file.

**Comment by digitalcraftsman** [comment]
Hello @blackmatch,

what exactly do you mean with "article"? If your refer to the project files under `exampleSite/data/projects` and it's description parameter your can use the normal markdown syntax to include images:

```
![](/path/to/image.png)
```

Drop your image in the `static` folder and create a relative link to the file like above. 

> can you tell me how to edit my article in multi-line

Are you trying to use a multi-line string within the YAML files?

Otherwise, please give more information about your problem(s).

**Comment by digitalcraftsman** [comment]
Reopen this issue if you still have questions.
