### ISSUE TITLE
A way to turn off sections

### ISSUE THREAD

**Issue by bep** [digitalcraftsman/hugo-agency-theme#16]
This is a very nice theme; I had a super-good-looking site up and running in two languages in no time.

But, I'm not ready with all the sections yet -- and I may not need them all, so it would be nice to have a config options to turn off a section.

What I have done now is to just copy the index.html and comment out the sections not neede - but some flags and I wouldn't have to do that.

**Comment by digitalcraftsman** [comment]
Thanks. I've added the flags to the config file. Just add a variable called `hide` to each section and set it either to true or false. See b668d143e998916da32eacf94cc2b6f61c8f1a3e.

Note that I added a new wrapper for the [clients section](https://github.com/digitalcraftsman/hugo-agency-theme/blob/master/exampleSite/config.toml#L172-L173) because those are defined in an array.

**Comment by bep** [comment]
I'm not sure how these conditionals work, but I shouldn't have to add `hide=false`; that should be the default.

**Comment by digitalcraftsman** [comment]
Ok. I did it vice versa.  A partial shows up if `enable = true` is set for it in the config file. This is the default case for the config file in `exampleSite` (because an empty demo page would look weird).

The partials shouldn't show up with your config file since this values aren't set.

**Comment by bep** [comment]
... ok, so the sections are default on?

**Comment by digitalcraftsman** [comment]
The sections are **disabled** in your case because you didn't set the appropriate variables. 

But new theme users will see them because the config file from `exampleSite` has these variables set by default.
