### ISSUE TITLE
Some inconsistency between themes

### ISSUE THREAD

**Issue by bep** [digitalcraftsman/hugo-agency-theme#18]
In Creative it's called /img/header.jpg

Here it's called something else.  

It would be nice if there were some naming conventions among these similar themes.

**Comment by digitalcraftsman** [comment]
Hi @bep,

while porting both themes I left everything as in the original themes. Both were created by the same person (BlackrockDigital). However, the filename of the background image is sort of "hard-coded" in the [stylesheets](https://github.com/digitalcraftsman/hugo-creative-theme/blob/c151ee4aca07aa939797df03dd6278d80d0a567b/static/css/creative.css#L190). 

I could change it for more consistency. But this would also mean that future updates of the stylesheets from the original theme need to be diffed in order to keep the chagens I've made.

But I could rename the file if you prefer it.

**Comment by digitalcraftsman** [comment]
Any updates here?
