### ISSUE TITLE
Single page layout

### ISSUE THREAD

**Issue by stp-ip** [digitalcraftsman/hugo-agency-theme#41]
Add single page layout. Usable for things like "about us", "disclaimer", "terms" etc.

Optional contacts form, which can be enabled per page.

Stretch: Use for blog layout: #22

**Comment by stp-ip** [comment]
Maybe optional contacts form on each page (config per page)

**Comment by digitalcraftsman** [comment]
I like the idea to extend this theme with more layouts. I already had people that used theme as homepage and liked in the menu to other sub-pages, like a blog.

Since the frame for each layout will be more or less the same, we could use of [`block templates`](https://gohugo.io/templates/blocks/).

What do you think how much complexity does this in the config file? It's fine that the theme is configurable but this also introduces a bunch of new variables. Sometimes I regret my design decision to put everything in the config file rather than keeping it flat. This was one of my earlier themes while learning Hugo.

Today, I would relocate a lot of stuff into data files, e.g. the defintion of services, projects and team members. Strings could be replaced with the `i18n` template function that was introduced with Hugo v0.17.

But this would also mean that the theme is in no way backwards-compatible and a lot of sites would break; it's a tradeoff with pros and cons.

**Comment by stp-ip** [comment]
Probably best to first add the functionality maybe via block templates and then do sort of a new release, which moves everything into data files. For now I just went with the current style. But would also prefer only configuration in the config file.

I'll finish up the current fixes and will try to think about the layout ideas tomorrow. Maybe I can get a PoC out with the old style and then we can move that to data files and i18n.

Does that make sense?

**Comment by digitalcraftsman** [comment]
Thank your for your feedback.

> Probably best to first add the functionality maybe via block templates and then do sort of a new release, which moves everything into data files. 

Since this are major changes that affect a larger user base it makes sense to version this theme in the future.

**Comment by stp-ip** [comment]
Yes for now I tried to make every change backwards compatible.
Maybe the data files + single page layout additions could be v1.

**Comment by maxheld83** [comment]
this is now included as per #66 correct?
I'd love this feature (and the theme), I am just a little lost without documentation on the single page layouts.
Perhaps you could replace the terms and privacy links in the example site with some actual single paged placeholders?

**Comment by stp-ip** [comment]
Was off the grid for a 2 week vacation. Will try to work on finishing up the smaller issues and new documentation in the coming week.

**Comment by stp-ip** [comment]
There is still an issue with hugo not really supporting single page sites (only via data files, which doesn't seem right). Will try to push a workaround and hopefully an actual solution asap.

**Comment by stp-ip** [comment]
As hugo-agency-theme is mostly in maintenance mode and no new features will be added.
We created [Syna](https://syna.okkur.org) as a more flexible iteration of this theme.

Syna can create a single page layout.
